schemaVersion: 1.0.0-alpha.1
name: whalesay
version: 0.2.0
description: "An example bundle that uses docker through the magic of whalespeak"
registry: ghcr.io/getporter

required:
  - docker

parameters:
  - name: msg
    description: a message for the whales to speak
    type: string
    default: "whale hello there!"
    applyTo:
      - say

mixins:
  - docker

install:
  - docker:
      run:
        image: "docker/whalesay:latest"
        rm: true
        arguments:
          - cowsay
          - Hello World
      
upgrade:
  - docker:
      run:
        image: "docker/whalesay:latest"
        rm: true
        arguments:
          - cowsay
          - World 2.0

say:
  - docker:
      run:
        image: "docker/whalesay:latest"
        rm: true
        arguments:
          - cowsay
          - "{{ bundle.parameters.msg }}"

uninstall:
  - docker:
      run:
        image: "docker/whalesay:latest"
        rm: true
        arguments:
          - cowsay
          - Goodbye World
