# These settings are synced to GitHub by https://probot.github.io/apps/settings/

# Labels: define labels for Issues and Pull Requests
labels:
  - name: "0 - ğŸš¨ğŸ©"
    color: "#731aef"
    description: "Emergency donuts come first"
  - name: "1 - ğŸ«"
    color: "#731aef"
    description: "Eat chocolate _after_ emergency donuts"
  - name: "2 - ğŸ•"
    color: "#731aef"
    description: "Pizza should be eaten daily"
  - name: "breaking change ğŸ’¥"
    color: "#081875"
    description: "Breaking changes to Porter's CLI, config or behavior "
  - name: "bug"
    color: "#d73a4a"
    description: "Oops, sorry!"
  - name: "cnab"
    color: "Related to the CNAB Specification"
    description: "#75aa11"
  - name: "design ğŸš²ğŸ "
    color: "#80bc20"
    description: "Bust out your paint chips, it's time to bikeshed."
  - name: "docs"
    color: "#b5d8f4"
    description: "Markdown ahoy! Updates needed on porter.sh or in dev docs."
  - name: "duplicate"
    color: "#C0C0C0"
    description: "This issue or pull request already exists"
  - name: "enhancement"
    color: "#80bc20"
    description: "New code incoming!"
  - name: "gap"
    color: "#d73a4a"
    description: "We missed a spot"
  - name: "good first issue"
    color: "#7057ff"
    description: "Good for new contributors"
  - name: "hacktoberfest-accepted"
    color: "##C0C0C0"
    description: "Give credit to a PR for hacktoberfest"
  - name: "help wanted"
    color: "#7057ff"
    description: "Good for someone who has contributed before"
  - name: "hmm ğŸ›‘ğŸ¤”"
    color: "#333333"
    description: "Needs more thinking time. Don't start on it yet, please."
  - name: "meta"
    color: "#b5d8f4"
    description: "Things necessary to make this project run day to day"
  - name: "mixin idea"
    color: "#a2eeef"
    description: "Suggest a new mixin"
  - name: "needs-pep"
    color: "#80bc20"
    description: "This change should go through the PEP process"
  - name: "Needs More Input  ğŸ¦–ğŸ¤–"
    color: "#d876e3"
    description: "Go back and fill in context and explain how to implement"
  - name: "nope"
    color: "#C0C0C0"
    description: "This will not be worked on, #SorryNotSorry"
  - name: "plugin idea"
    color: "#a2eeef"
    description: "Suggest a new plugin"
  - name: "question"
    color: "#d876e3"
    description: "Halp plz"
  - name: "security ğŸ”’"
    color: "#d73a4a"
    description: "Security issues, bugs and features"
  - name: "suggestion"
    color: "#d876e3"
    description: "Idea for maintainers to consider. Do not take this issue until triaged."
  - name: "user experience ğŸŒˆğŸ’–"
    color: "#081875"
    description: "All Hail the UX Gods"
  - name: "website"
    color: "#b5d8f4"
    description: "Great for people with graphic design and html/css skills"


# See https://developer.github.com/v3/teams/#add-or-update-team-repository for available options
# The permission to grant the team. Can be one of:
# * `pull` - can pull, but not push to or administer this repository.
# * `push` - can pull and push, but not administer this repository.
# * `admin` - can pull, push and administer this repository.
# * `maintain` - Recommended for project managers who need to manage the repository without access to sensitive or destructive actions.
# * `triage` - Recommended for contributors who need to proactively manage issues and pull requests without write access.
teams:
  - name: getporter/admins
    permission: admin
  - name: getporter/maintainers
    permission: maintain
  - name: getporter/triage
    permission: triage
  - name: getporter/bots
    permission: push
