# Example configuration for the webserver
# at https://github.com/monopole/hello
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: my-hello

resources:
- deployment.yaml
- service.yaml
- configMap.yaml
