[settings]
  ID = "porter"

[build]
  publish = "docs/public"
  command = "make docs"

[build.environment]
  HUGO_VERSION = "0.78.1"

[context.branch-deploy]
  command = "make docs BASEURL=$DEPLOY_PRIME_URL/"
  
[context.deploy-preview]
  command = "make docs BASEURL=$DEPLOY_PRIME_URL/"