[[headers]]
# Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"

[settings]
  ID = "porter"

[build]
  publish = "docs/public"
  command = "go run mage.go -v Docs"

[build.environment]
  HUGO_VERSION = "0.118.2"
  GO_VERSION = "1.20"

[context.branch-deploy]
  command = "go run mage.go -v DocsBranchPreview"

[context.deploy-preview]
  command = "go run mage.go -v DocsPullRequestPreview"
