baseURL = "https://porter.sh/"
languageCode = "en-us"
title = "Porter"
theme = "porter"
canonifyURLs = "false"
relativeURLs = "false"
pluralizeListTitles = "false"
plainIdAnchors = "true"
defaultContentLanguage = "en"

# Syntax Highlighting
pygmentsUseClasses = true
pygmentsStyle = "friendly"

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark.renderer]
    unsafe = true

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Default Page Parameters
[params]
  title = "Porter"
  author = "Carolyn Van Slyck"
  description = "A Friendly Cloud Installer for Cloud Native Application Bundles"
  image = "images/porter-twitter-card.png"

# Docs Navigation
[[menu.main]]
  name = "Get Started"
  identifier = "get-started"
  weight = 2
  url = "#"
  [[menu.main]]
    name = "Install Porter"
    url = "/install"
    identifier = "install"
    weight = 11
    parent = "get-started"
  [[menu.main]]
    name = "QuickStart"
    url = "/quickstart"
    identifier = "quickstart"
    weight = 12
    parent = "get-started"
  
[[menu.main]]
  name = "Contribute"
  url = "/contribute/"
  identifier = "contribute"
  weight = 50
  [[menu.main]]
    name = "New Contributor Guide"
    url = "/contribute/"
    identifier = "contribute-overview"
    weight = 51
    parent = "contribute"
  [[menu.main]]
    name = "Contributing Tutorial"
    url = "/contribute/tutorial/"
    identifier = "contributing-tutorial"
    weight = 52
    parent = "contribute"
  [[menu.main]]
    name = "Contributing Guide"
    url = "/contribute/guide/"
    identifier = "contributing-guide"
    weight = 53
    parent = "contribute"
  [[menu.main]]
    name = "Make a Proposal"
    url = "/contribute/proposals/"
    identifier = "proposals"
    weight = 54
    parent = "contribute"

[[menu.main]]
  name = "Porter Commands"
  url = "/cli"
  identifier = "cli"
  weight = 102
  [[menu.main]]
    name = "Overview"
    url = "/cli/porter/#see-also"
    identifier = "cli-overview"
    weight = 103
    parent = "cli"
  [[menu.main]]
    name = "Bundles"
    url = "/cli/porter_bundles"
    identifier = "cli-bundles"
    weight = 123
    parent = "cli"
  [[menu.main]]
    name = "Credentials"
    url = "/cli/porter_credentials"
    identifier = "cli-credentials"
    weight = 124
    parent = "cli"
  [[menu.main]]
    name = "Parameters"
    url = "/cli/porter_parameters"
    identifier = "cli-parameters"
    weight = 125
    parent = "cli"
  [[menu.main]]
    name = "Installations"
    url = "/cli/porter_installations"
    identifier = "cli-installations"
    weight = 126
    parent = "cli"
  [[menu.main]]
    name = "Mixins"
    url = "/cli/porter_mixins"
    identifier = "cli-mixins"
    weight = 127
    parent = "cli"
  [[menu.main]]
    name = "Plugins"
    url = "/cli/porter_plugins"
    identifier = "cli-plugins"
    weight = 128
    parent = "cli"

[[menu.main]]
  name = "Mixins"
  identifier = "mixins"
  weight = 200
  [[menu.main]]
    name = "Overview"
    identifier = "mixins-overview"
    weight = 201
    url = "/mixins"
    parent = "mixins"
  [[menu.main]]
    name = "Develop Mixins"
    url = "/mixin-dev-guide/"
    identifier = "mixin-dev-guide"
    weight = 202
    parent = "mixins"
  [[menu.main]]
    name = "Distribute Mixins"
    url = "/mixin-dev-guide/distribution/"
    identifier = "mixin-distribution"
    weight = 203
    parent = "mixins"
  [[menu.main]]
    name = "Mixin Architecture"
    url = "/mixin-dev-guide/architecture/"
    identifier = "mixin-architecture"
    weight = 204
    parent = "mixins"

[[menu.main]]
  name = "Plugins"
  identifier = "plugins"
  weight = 250
  [[menu.main]]
    name = "Overview"
    identifier = "plugins-overview"
    weight = 251
    url = "/plugins"
    parent = "plugins"
  [[menu.main]]
    name = "Types"
    identifier = "plugin-types"
    weight = 252
    url = "/plugins/types"
    parent = "plugins"

[[menu.main]]
  name = "Author Bundles"
  identifier = "author-bundles"
  weight = 300
  [[menu.main]]
    name = "Overview"
    url = "/author-bundles"
    identifier = "author-bundles-overview"
    weight = 301
    parent = "author-bundles"
  [[menu.main]]
    name = "Custom Dockerfile"
    url = "/custom-dockerfile/"
    identifier = "custom-dockerfile"
    weight = 302
    parent = "author-bundles"
  [[menu.main]]
    name = "Mixins"
    url = "/use-mixins"
    identifier = "use-mixins"
    weight = 303
    parent = "author-bundles"
  [[menu.main]]
    name = "Dependencies"
    url = "/dependencies"
    identifier = "dependencies"
    weight = 304
    parent = "author-bundles"
  [[menu.main]]
    name = "Parameters, Credentials and Outputs"
    url = "/wiring"
    identifier = "wiring"
    weight = 305
    parent = "author-bundles"

[[menu.main]]
  name = "Distribute Bundles"
  identifier = "distribute-bundles"
  weight = 310
  [[menu.main]]
    name = "Overview"
    url = "/distribute-bundles"
    identifier = "distribute-bundles-overview"
    weight = 311
    parent = "distribute-bundles"
  [[menu.main]]
    name = "Copy Bundles"
    identifier = "copy-bundles"
    url = "/copy-bundles"
    weight = 312
    parent = "distribute-bundles"
  [[menu.main]]
    name = "Archive Bundles"
    identifier = "archive-bundles"
    url = "/archive-bundles"
    weight = 313
    parent = "distribute-bundles"
  [[menu.main]]
    name = "Compatible Registries"
    identifier = "compatible-registries"
    url = "/compatible-registries/"
    weight = 314
    parent = "distribute-bundles"

[[menu.main]]
  name = "Examine Bundles"
  identifier = "examine-bundles"
  weight = 325
  [[menu.main]]
    name = "Overview"
    url = "/examine-bundles"
    identifier = "examine-bundles-overview"
    weight = 326
    parent = "examine-bundles"
  [[menu.main]]
    name = "Inspect Bundle Images"
    url = "/inspect-bundles/"
    identifier = "inspect-bundles"
    weight = 327
    parent = "examine-bundles"

[[menu.main]]
  name = "Porter Architecture"
  identifier = "porter-architecture"
  weight = 400
  [[menu.main]]
    name = "Overview"
    url = "/architecture"
    identifier = "architecture"
    weight = 401
    parent = "porter-architecture"
  [[menu.main]]
    name = "CNAB"
    url = "/cnab/"
    identifier = "architecture-cnab"
    weight = 402
    parent = "porter-architecture"
  [[menu.main]]
    name = "Buildtime"
    url = "/architecture-buildtime"
    identifier = "architecture-buildtime"
    weight = 403
    parent = "porter-architecture"
  [[menu.main]]
    name = "Runtime"
    url = "/architecture-runtime"
    identifier = "architecture-runtime"
    weight = 404
    parent = "porter-architecture"
  [[menu.main]]
    name = "Invocation Images"
    url = "/build-image"
    identifier = "build-image"
    weight = 405
    parent = "porter-architecture"
  [[menu.main]]
    name = "Credentials"
    url = "/credentials/"
    identifier = "credentials"
    weight = 406
    parent = "porter-architecture"
  [[menu.main]]
    name = "Parameters"
    url = "/parameters/"
    identifier = "parameters"
    weight = 407
    parent = "porter-architecture"

[[menu.main]]
  name = "FAQ"
  identifier = "faq"
  url = "/faq"
  weight = 500

[[menu.main]]
  name = "Troubleshooting"
  identifier = "troubleshooting"
  url = "/troubleshooting"
  weight = 501

[[menu.main]]
  name = "Best Practices"
  url = "/best-practices/"
  identifier = "best-practices"
  weight = 600

[[menu.main]]
  name = "References"
  identifier = "references"
  weight = 1000
  [[menu.main]]
    name = "Configuration"
    url = "/configuration"
    identifier = "configuration"
    weight = 1010
    parent = "references"
  [[menu.main]]
    name = "Docker Images"
    url = "/docker-images/"
    identifer = "docker-images"
    weight = 1011
    parent = "references"
  [[menu.main]]
    name = "Logos"
    url = "/logo/"
    identifer = "logo"
    weight = 1011
    parent = "references"
  [[menu.main]]
    name = "CNAB Spec"
    url = "https://deislabs.io/cnab"
    identifier = "cnab"
    weight = 1020
    parent = "references"
    
