baseURL = "https://porter.sh/"
languageCode = "en-us"
title = "Porter"
theme = "porter"

# Docs Navigation

[params]
  title = "Porter"
  author = "Carolyn Van Slyck"
  description = "A Friendly Cloud Installer for Cloud Native Application Bundles"

canonifyURLs = "false"
relativeURLs = "true"
pluralizeListTitles = "false"
plainIdAnchors = "true"
defaultContentLanguage = "en"

[[menu.main]]
  name = "Get Started"
  identifier = "get-started"
  weight = 2
  [[menu.main]]
    name = "Install Porter"
    url = "/install"
    identifier = "install"
    weight = 11
    parent = "get-started"
  [[menu.main]]
    name = "QuickStart"
    url = "/quickstart"
    identifier = "quickstart"
    weight = 12
    parent = "get-started"

[[menu.main]]
  name = "Porter Commands"
  url = "/cli"
  identifier = "cli"
  weight = 102
  [[menu.main]]
    name = "porter create"
    url = "/cli/porter_create"
    identifier = "cli-create"
    weight = 123
    parent = "cli"
  [[menu.main]]
    name = "porter build"
    url = "/cli/porter_build"
    identifier = "cli-build"
    weight = 124
    parent = "cli"
  [[menu.main]]
    name = "porter install"
    url = "/cli/porter_install"
    identifier = "cli-install"
    weight = 125
    parent = "cli"
  [[menu.main]]
    name = "porter invoke"
    url = "/cli/porter_invoke"
    identifier = "cli-invoke"
    weight = 126
    parent = "cli"
  [[menu.main]]
    name = "porter upgrade"
    url = "/cli/porter_upgrade"
    identifier = "cli-upgrade"
    weight = 127
    parent = "cli"
  [[menu.main]]
    name = "porter uninstall"
    url = "/cli/porter_uninstall"
    identifier = "cli-uninstall"
    weight = 128
    parent = "cli"
  [[menu.main]]
    name = "porter list"
    url = "/cli/porter_list"
    identifier = "cli-list"
    weight = 129
    parent = "cli"
  [[menu.main]]
    name = "porter show"
    url = "/cli/porter_show"
    identifier = "cli-show"
    weight = 129
    parent = "cli"
  [[menu.main]]
    name = "porter instances output list"
    url = "/cli/porter_instances_output_list"
    identifier = "cli-instances-output-list"
    weight = 130
    parent = "cli"
  [[menu.main]]
    name = "porter instances output show"
    url = "/cli/porter_instances_output_show"
    identifier = "cli-instances-output-show"
    weight = 131
    parent = "cli"
  [[menu.main]]
    name = "porter mixins list"
    url = "/cli/porter_mixins_list/"
    identifier = "cli-mixins-list"
    weight = 140
    parent = "cli"
  [[menu.main]]
    name = "porter mixins install"
    url = "/cli/porter_mixins_install/"
    identifier = "cli-mixins-install"
    weight = 141
    parent = "cli"
  [[menu.main]]
    name = "porter mixins uninstall"
    url = "/cli/porter_mixins_uninstall/"
    identifier = "cli-mixins-uninstall"
    weight = 142
    parent = "cli"
  [[menu.main]]
    name = "porter mixins feed template"
    url = "/cli/porter_mixins_feed_template"
    identifier = "cli-mixins-feed-template"
    weight = 150
    parent = "cli"
  [[menu.main]]
    name = "porter mixins feed generate"
    url = "/cli/porter_mixins_feed_generate"
    identifier = "cli-mixins-feed-generate"
    weight = 151
    parent = "cli"
  [[menu.main]]
    name = "porter copy"
    url = "/cli/porter_copy"
    identifier = "cli-copy"
    weight = 160
    parent = "cli"
  [[menu.main]]
    name = "porter archive"
    url = "/cli/porter_archive"
    identifier = "cli-archive"
    weight = 161
    parent = "cli"
  [[menu.main]]
    name = "porter schema"
    url = "/cli/porter_schema"
    identifier = "cli-schema"
    weight = 198
    parent = "cli"
  [[menu.main]]
    name = "porter plugins list"
    url = "/cli/porter_plugins_list/"
    identifier = "cli-plugins-list"
    weight = 165
    parent = "cli"
  [[menu.main]]
    name = "porter version"
    url = "/cli/porter_version"
    identifier = "cli-version"
    weight = 199
    parent = "cli"

[[menu.main]]
  name = "Mixins"
  identifier = "mixins"
  weight = 200
  [[menu.main]]
  name = "Overview"
  identifier = "mixins-overview"
  weight = 201
  url = "/mixins"
  parent = "mixins"
  [[menu.main]]
    name = "exec"
    identifier = "exec-mixin"
    weight = 202
    url = "/mixins/exec"
    parent = "mixins"
  [[menu.main]]
    name = "helm"
    identifier = "helm-mixin"
    weight = 203
    url = "/mixins/helm"
    parent = "mixins"
  [[menu.main]]
    name = "kubernetes"
    identifier = "kubernetes-mixin"
    weight = 204
    url = "/mixins/kubernetes"
    parent = "mixins"
  [[menu.main]]
    name = "arm"
    identifier = "arm-mixin"
    weight = 210
    url = "/mixins/arm"
    parent = "mixins"
  [[menu.main]]
    name = "aws"
    identifier = "aws-mixin"
    weight = 211
    url = "/mixins/aws"
    parent = "mixins"
  [[menu.main]]
    name = "az"
    identifier = "az-mixin"
    weight = 212
    url = "/mixins/az"
    parent = "mixins"
  [[menu.main]]
    name = "gcloud"
    identifier = "gcloud-mixin"
    weight = 213
    url = "/mixins/gcloud"
    parent = "mixins"
  [[menu.main]]
    name = "terraform"
    identifier = "terraform-mixin"
    weight = 214
    url = "/mixins/terraform"
    parent = "mixins"

[[menu.main]]
  name = "Author Bundles"
  identifier = "author-bundles"
  weight = 300
  [[menu.main]]
    name = "Overview"
    url = "/author-bundles"
    identifier = "author-bundles-overview"
    weight = 301
    parent = "author-bundles"
  [[menu.main]]
    name = "Custom Dockerfile"
    url = "/custom-dockerfile/"
    identifier = "custom-dockerfile"
    weight = 302
    parent = "author-bundles"
  [[menu.main]]
    name = "Mixins"
    url = "/use-mixins"
    identifier = "use-mixins"
    weight = 303
    parent = "author-bundles"
  [[menu.main]]
    name = "Dependencies"
    url = "/dependencies"
    identifier = "dependencies"
    weight = 304
    parent = "author-bundles"
  [[menu.main]]
    name = "Parameters, Credentials and Outputs"
    url = "/wiring"
    identifier = "wiring"
    weight = 305
    parent = "author-bundles"

[[menu.main]]
  name = "Distribute Bundles"
  identifier = "distribute-bundles"
  weight = 310
  [[menu.main]]
    name = "Overview"
    url = "/distribute-bundles"
    identifier = "distribute-bundles-overview"
    weight = 311
    parent = "distribute-bundles"
  [[menu.main]]
    name = "Copy Bundles"
    identifier = "copy-bundles"
    url = "/copy-bundles"
    weight = 312
    parent = "distribute-bundles"
  [[menu.main]]
    name = "Archive Bundles"
    identifier = "archive-bundles"
    url = "/archive-bundles"
    weight = 313
    parent = "distribute-bundles"
  [[menu.main]]
    name = "Compatible Registries"
    identifier = "compatible-registries"
    url = "/compatible-registries/"
    weight = 314
    parent = "distribute-bundles"

[[menu.main]]
  name = "Examine Bundles"
  identifier = "examine-bundles"
  weight = 325
  [[menu.main]]
    name = "Overview"
    url = "/examine-bundles"
    identifier = "examine-bundles-overview"
    weight = 326
    parent = "examine-bundles"
  [[menu.main]]
    name = "Inspect Bundle Images"
    url = "/inspect-bundle"
    identifier = "inspect-bundles"
    weight = 327
    parent = "examine-bundles"


[[menu.main]]
  name = "Develop Mixins"
  identifier = "develop-mixins"
  weight = 350
  [[menu.main]]
    name = "Overview"
    url = "/mixin-dev-guide/"
    identifier = "mixin-dev-guide"
    weight = 351
    parent = "develop-mixins"
  [[menu.main]]
    name = "Commands"
    url = "/mixin-dev-guide/commands/"
    identifier = "mixin-commands"
    weight = 353
    parent = "develop-mixins"
  [[menu.main]]
    name = "Test"
    url = "/mixin-dev-guide/test/"
    identifier = "mixin-test"
    weight = 355
    parent = "develop-mixins"
  [[menu.main]]
    name = "Mixin Architecture"
    url = "/mixin-dev-guide/architecture/"
    identifier = "mixin-architecture"
    weight = 360
    parent = "develop-mixins"
  [[menu.main]]
    name = "Distribute Mixins"
    url = "/mixin-dev-guide/distribution/"
    identifier = "mixin-distribution"
    weight = 361
    parent = "develop-mixins"

[[menu.main]]
  name = "Porter Architecture"
  identifier = "porter-architecture"
  weight = 400
  [[menu.main]]
    name = "Overview"
    url = "/architecture"
    identifier = "architecture"
    weight = 401
    parent = "porter-architecture"
  [[menu.main]]
    name = "Buildtime"
    url = "/architecture-buildtime"
    identifier = "architecture-buildtime"
    weight = 402
    parent = "porter-architecture"
  [[menu.main]]
    name = "Runtime"
    url = "/architecture-runtime"
    identifier = "architecture-runtime"
    weight = 403
    parent = "porter-architecture"
  [[menu.main]]
    name = "Invocation Images"
    url = "/build-image"
    identifier = "build-image"
    weight = 404
    parent = "porter-architecture"

[[menu.main]]
  name = "FAQ"
  identifier = "faq"
  url = "/faq"
  weight = 500

[[menu.main]]
  name = "Troubleshooting"
  identifier = "troubleshooting"
  url = "/troubleshooting"
  weight = 501

[[menu.main]]
  name = "Best Practices"
  url = "/best-practices/"
  identifier = "best-practices"
  weight = 600

[[menu.main]]
  name = "References"
  identifier = "references"
  weight = 1000
  [[menu.main]]
    name = "Configuration"
    url = "/configuration"
    identifier = "configuration"
    weight = 1010
    parent = "references"
  [[menu.main]]
    name = "Docker Images"
    url = "/docker-images/"
    identifer = "docker-images"
    weight = 1011
    parent = "references"
  [[menu.main]]
    name = "CNAB Spec"
    url = "https://deislabs.io/cnab"
    identifier = "cnab"
    weight = 1020
    parent = "references"

