baseURL = "/"
languageCode = "en-us"
title = "Porter"
theme = "porter"

# Docs Navigation

[params]
  title = "Porter"
  author = "Carolyn Van Slyck"
  description = "A Friendly Cloud Installer for Cloud Native Application Bundles"

canonifyURLs = "false"
relativeURLs = "true"
pluralizeListTitles = "false"
plainIdAnchors = "true"
defaultContentLanguage = "en"

[[menu.main]]
  name = "Getting Started"
  url = "/getting-started"
  identifier = "getting-started"
  weight = 2
  [[menu.main]]
    name = "Install Porter"
    url = "/install"
    identifier = "install"
    weight = 11
    parent = "getting-started"
  [[menu.main]]
    name = "QuickStart"
    url = "/quickstart"
    identifier = "quickstart"
    weight = 12
    parent = "getting-started"
  #[[menu.main]]
  #  name = "Finding Bundles"
  #  url = "/finding-bundles"
  #  identifier = "finding-bundles"
  #  weight = 16
  #  parent = "getting-started"

[[menu.main]]
  name = "Porter Commands"
  url = "/cli"
  identifier = "cli"
  weight = 102
  [[menu.main]]
    name = "porter create"
    url = "/cli#porter-create"
    identifier = "cli-create"
    weight = 123
    parent = "cli"
  [[menu.main]]
    name = "porter build"
    url = "/cli#porter-build"
    identifier = "cli-build"
    weight = 124
    parent = "cli"
  [[menu.main]]
    name = "porter install"
    url = "/cli#porter-install"
    identifier = "cli-install"
    weight = 125
    parent = "cli"
  [[menu.main]]
    name = "porter invoke"
    url = "/cli#porter-invoke"
    identifier = "cli-invoke"
    weight = 126
    parent = "cli"
  [[menu.main]]
    name = "porter upgrade"
    url = "/cli#porter-upgrade"
    identifier = "cli-upgrade"
    weight = 127
    parent = "cli"
  [[menu.main]]
    name = "porter uninstall"
    url = "/cli#porter-uninstall"
    identifier = "cli-uninstall"
    weight = 128
    parent = "cli"
  [[menu.main]]
    name = "porter list"
    url = "/cli#porter-list"
    identifier = "cli-list"
    weight = 129
    parent = "cli"
  [[menu.main]]
    name = "porter show"
    url = "/cli#porter-show"
    identifier = "cli-show"
    weight = 129
    parent = "cli"
  [[menu.main]]
    name = "porter instances output list"
    url = "/cli#porter-instances-output-list"
    identifier = "cli-instances-output-list"
    weight = 130
    parent = "cli"
  [[menu.main]]
    name = "porter instances output show"
    url = "/cli#porter-instances-output-show"
    identifier = "cli-instances-output-show"
    weight = 131
    parent = "cli"
  [[menu.main]]
    name = "porter mixins list"
    url = "/cli#porter-mixins-list"
    identifier = "cli-mixins-list"
    weight = 140
    parent = "cli"
  [[menu.main]]
    name = "porter mixins feed template"
    url = "/cli#porter-mixins-feed-template"
    identifier = "cli-mixins-feed-template"
    weight = 150
    parent = "cli"
  [[menu.main]]
    name = "porter mixins feed generate"
    url = "/cli#porter-mixins-feed-generate"
    identifier = "cli-mixins-feed-generate"
    weight = 151
    parent = "cli"
  [[menu.main]]
    name = "porter schema"
    url = "/cli#porter-schema"
    identifier = "cli-schema"
    weight = 198
    parent = "cli"
  [[menu.main]]
    name = "porter version"
    url = "/cli#porter-version"
    identifier = "cli-version"
    weight = 199
    parent = "cli"
[[menu.main]]
  name = "Mixins"
  identifier = "mixins"
  weight = 200
  [[menu.main]]
  name = "Overview"
  identifier = "mixins-overview"
  weight = 201
  url = "/mixins"
  parent = "mixins"
  [[menu.main]]
    name = "exec"
    identifier = "exec-mixin"
    weight = 202
    url = "/mixins/exec"
    parent = "mixins"
  [[menu.main]]
    name = "helm"
    identifier = "helm-mixin"
    weight = 203
    url = "/mixins/helm"
    parent = "mixins"
  [[menu.main]]
    name = "kubernetes"
    identifier = "kubernetes-mixin"
    weight = 204
    url = "/mixins/kubernetes"
    parent = "mixins"
  [[menu.main]]
    name = "az"
    identifier = "az-mixin"
    weight = 210
    url = "/mixins/az"
    parent = "mixins"
  [[menu.main]]
    name = "azure"
    identifier = "azure-mixin"
    weight = 211
    url = "/mixins/azure"
    parent = "mixins"
  [[menu.main]]
    name = "aws"
    identifier = "aws-mixin"
    weight = 212
    url = "/mixins/aws"
    parent = "mixins"
  [[menu.main]]
    name = "gcloud"
    identifier = "gcloud-mixin"
    weight = 213
    url = "/mixins/gcloud"
    parent = "mixins"
  [[menu.main]]
    name = "terraform"
    identifier = "terraform-mixin"
    weight = 214
    url = "/mixins/terraform"
    parent = "mixins"
[[menu.main]]
  name = "Authoring Bundles"
  identifier = "authoring-bundles"
  weight = 300
  [[menu.main]]
    name = "Overview"
    url = "/authoring-bundles"
    identifier = "authoring-bundles-overview"
    weight = 301
    parent = "authoring-bundles"
  [[menu.main]]
    name = "Using Mixins"
    url = "/using-mixins"
    identifier = "using-mixins"
    weight = 302
    parent = "authoring-bundles"
  [[menu.main]]
    name = "Dependencies"
    url = "/dependencies"
    identifier = "dependencies"
    weight = 303
    parent = "authoring-bundles"
  [[menu.main]]
    name = "Using Parameters, Credentials and Outputs"
    url = "/wiring"
    identifier = "wiring"
    weight = 303
    parent = "authoring-bundles"

[[menu.main]]
  name = "Developing Mixins"
  identifier = "developing-mixins"
  weight = 350
  [[menu.main]]
    name = "Overview"
    url = "/mixin-dev-guide"
    identifier = "mixin-dev-guide"
    weight = 351
    parent = "developing-mixins"
  [[menu.main]]
    name = "Commands"
    url = "/mixin-commands"
    identifier = "mixin-commands"
    weight = 353
    parent = "developing-mixins"
  [[menu.main]]
    name = "Mixin Architecture"
    url = "/mixin-architecture"
    identifier = "mixin-architecture"
    weight = 360
    parent = "developing-mixins"
  [[menu.main]]
    name = "Distributing Mixins"
    url = "/mixin-distribution"
    identifier = "mixin-distribution"
    weight = 361
    parent = "developing-mixins"

[[menu.main]]
  name = "Porter Architecture"
  identifier = "porter-architecture"
  weight = 400
  [[menu.main]]
    name = "Overview"
    url = "/architecture"
    identifier = "architecture"
    weight = 401
    parent = "porter-architecture"
  [[menu.main]]
    name = "Buildtime"
    url = "/architecture-buildtime"
    identifier = "architecture-buildtime"
    weight = 402
    parent = "porter-architecture"
  [[menu.main]]
    name = "Runtime"
    url = "/architecture-runtime"
    identifier = "architecture-runtime"
    weight = 403
    parent = "porter-architecture"
  [[menu.main]]
    name = "Invocation Images"
    url = "/build-image"
    identifier = "build-image"
    weight = 404
    parent = "porter-architecture"

[[menu.main]]
  name = "FAQ"
  identifier = "faq"
  url = "/faq"
  weight = 500

[[menu.main]]
  name = "References"
  identifier = "references"
  weight = 600
  [[menu.main]]
    name = "Configuration"
    url = "/configuration"
    identifier = "configuration"
    weight = 601
    parent = "references"
  [[menu.main]]
    name = "CNAB Spec"
    url = "https://deislabs.io/cnab"
    identifier = "cnab"
    weight = 610
    parent = "references"
