mixins:
  - exec
  - kubernetes

credentials:
  - name: kubeconfig
    path: /root/.kube/config

name: kubernetes 
version: 0.1.0
description: "An example Porter bundle with Kubernetes"
tag: getporter/kubernetes

install:
  - kubernetes:
      description: "Create NGINX Deployment"
      manifests:
        - manifests/nginx
      wait: true
      outputs:
        - name: IP_ADDRESS
          resourceType: service
          resourceName: nginx-deployment
          jsonPath: "{.spec.clusterIP}"
  - exec:
      description: "Echo the IP Address"
      command: ./helpers.sh
      arguments:
        - "dump-ip {{bundle.outputs.IP_ADDRESS}}"

uninstall:
  - kubernetes:
      description: "Uninstall Hello World"
      manifests:
        - manifests/nginx
      wait: true

outputs:
  - name: IP_ADDRESS
    type: string
